### ISSUE TITLE
Specification version 1.5 support

### ISSUE THREAD

**Issue by paulkoko** [CycloneDX/cyclonedx-go#109]
Are there plans to add support for 1.5?

**Comment by nscuro** [comment]
Hi @paulkoko, yes it is planned and I'm working on it. Just scrambling for time to complete it currently.

A good chunk is already done in https://github.com/CycloneDX/cyclonedx-go/pull/90, and some tiny parts are already merged to `master`.

**Comment by niclas-g** [comment]
> If you're willing and able to, you could help by either contributing missing parts in #90, or alternatively test the changes that currently exist in that branch, and let me know of any issues you run into.
> 
> If you have an existing code base you could test on with v1.5 BOMs, that'd be super helpful.
> 
I'll be happy to test against our codebase, I'll see if I can put some time towards it this week or next. 

> When you say you can't consume BOMs generated by Trivy, is it that info is being dropped, or is decoding failing entirely?

Decoding fails entirely, it returns an  `ErrInvalidSpecVersion` [here](https://github.com/CycloneDX/cyclonedx-go/blob/b1105ec828d6e3c502028a05f98e9fb4b574ab4d/cyclonedx_json.go#L45C2-L47) when it discovers that it's an unsupported version.

**Comment by nscuro** [comment]
> @niclas-g Decoding fails entirely, it returns an ErrInvalidSpecVersion [here](https://github.com/CycloneDX/cyclonedx-go/blob/b1105ec828d6e3c502028a05f98e9fb4b574ab4d/cyclonedx_json.go#L45C2-L47) when it discovers that it's an unsupported version.

Ah, I see. This is technically fixed in `master` already

https://github.com/CycloneDX/cyclonedx-go/blob/83031d6697bd6d8b20bce2a0326347a0ea7691c7/cyclonedx_json.go#L28-L62

For a short-term "solution" I could cut a v0.7.2 release, so that at least decoding works again. Would that help?

**Comment by niclas-g** [comment]
@nscuro, that would be great!

**Comment by nscuro** [comment]
@niclas-g Here we go: https://github.com/CycloneDX/cyclonedx-go/releases/tag/v0.7.2

Would still very much appreciate it if you could also test the [`spec-v1.5`](https://github.com/CycloneDX/cyclonedx-go/tree/spec-v1.5) branch with your code base! :)

**Comment by niclas-g** [comment]
Thanks @nscuro! I'll have a look at the release shortly and try out the branch against our code base next week.

**Comment by esnible** [comment]
Is there a list of 1.5 features that are not yet supported?  For example

- [modelcard](https://github.com/CycloneDX/cyclonedx-go/blob/83031d6697bd6d8b20bce2a0326347a0ea7691c7/schema/bom-1.5.schema.json#L585)
- [data](https://github.com/CycloneDX/cyclonedx-go/blob/83031d6697bd6d8b20bce2a0326347a0ea7691c7/schema/bom-1.5.schema.json#L589)
- signature
- additionalProperties
- attachment
- hash-alg
- condition

**Comment by esnible** [comment]
I am concerned about Metadata.Tools, https://github.com/CycloneDX/cyclonedx-go/blob/master/cyclonedx.go#L439

- In v1.4, `tools` is an array https://cyclonedx.org/docs/1.4/json/#metadata_tools
- In v1.5, `tools` is an object https://cyclonedx.org/docs/1.5/json/#metadata_tools_oneOf_i0_components

It seems like it will not be possible to deserialize both 1.4 and 1.5 SBOMs into the same structure.
