### ISSUE TITLE
Extend `EvidenceOccurrence`

### ISSUE THREAD

**Issue by mcombuechen** [CycloneDX/cyclonedx-go#156]
Type `EvidenceOccurrence` has been extended with new properties in spec 1.6.

* `lineNumber`
* `offset`
* `symbol`
* `additionalContext`

Resources:
* https://github.com/CycloneDX/specification/pull/325/files
* https://cyclonedx.org/docs/1.6/json/#components_items_evidence_occurrences

When adding these new properties to `type EvidenceOccurrence`, consider the conversion code for components in `convert.go` to achieve backwards compatibility with spec versions < v1.6.

**Comment by nscuro** [comment]
Implemented in #159
