### ISSUE TITLE
Add `License.Acknowledgement`

### ISSUE THREAD

**Issue by mcombuechen** [CycloneDX/cyclonedx-go#166]
This is to track the addition of the `"acknowledgement"` field to type `License` (spec 1.6).

See:
* https://cyclonedx.org/docs/1.6/json/#components_items_licenses_oneOf_i0_items_license_acknowledgement
* https://github.com/CycloneDX/specification/pull/408

**Comment by nscuro** [comment]
Implemented in #167.
