### ISSUE TITLE
Add `EnvironmentalConsiderations` to ML model

### ISSUE THREAD

**Issue by mcombuechen** [CycloneDX/cyclonedx-go#177]
This is to track the addition of new field `$.components[].modelCard.considerations.environmentalConsiderations` from spec version 1.6.

See:
* https://cyclonedx.org/docs/1.6/json/#components_items_modelCard_considerations_environmentalConsiderations
* https://github.com/CycloneDX/specification/pull/395

**Comment by nscuro** [comment]
Implemented in #178
