### ISSUE TITLE
[bug] BOMEncoder for vulnerabilities adds a default score of 0 if not specified

### ISSUE THREAD

**Issue by samj1912** [CycloneDX/cyclonedx-go#25]
Currently vulnerabilities.ratings.score is a non required field in the spec. The library however serializes absent scores as 0 in VEX documents. This is probably because score is a float field https://github.com/CycloneDX/cyclonedx-go/blob/6c388c44b4d7fe6f4715a8106b1bd49b0e22b446/cyclonedx.go#L637 instead of a float pointer in which case we could omit it in case it is set to nil.

For example see BOMs at https://github.com/anchore/grype/pull/678

**Comment by nscuro** [comment]
Good catch and thx for reporting, @samj1912! Fixed in [v0.5.1](https://github.com/CycloneDX/cyclonedx-go/releases/tag/v0.5.1).
