### ISSUE TITLE
Feature Request: JSON schema on JSON output

### ISSUE THREAD

**Issue by mcombuechen** [CycloneDX/cyclonedx-go#79]
The [CycloneDX JS lib](https://github.com/CycloneDX/cyclonedx-javascript-library) adds a `$schema` field to the JSON output, linking to the respective JSON schema definition file at cyclonedx.org. It would be nice to also get this on the output from this library.

### Example

```json
{
  "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "version": 1,
  ...
}
```

**Comment by nscuro** [comment]
Implemented in #80, thanks @mcombuechen!
